package com.mahghuuls.elusiveflora.world;

import com.mahghuuls.elusiveflora.ElusiveFloraLog;
import com.mahghuuls.elusiveflora.block.BlockPlantBase;
import com.mahghuuls.elusiveflora.block.PlantStage;
import com.mahghuuls.elusiveflora.config.PlantSettings;
import com.mahghuuls.elusiveflora.registry.PlantRegistry;
import com.mahghuuls.elusiveflora.roster.PlantDefinition;
import net.minecraft.block.state.IBlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraftforge.fml.common.IWorldGenerator;

import java.util.Random;

/**
 * Places plants when a chunk is generated, in every dimension. For each enabled plant whose
 * dimension matches: one roll against its chunk chance, then up to {@link #CANDIDATES}
 * candidate columns inside the chunk, placing at the first position {@link PlacementCheck} accepts. At most
 * one plant of each kind per chunk.
 *
 * <p>Columns are offset by 8 like vanilla decoration, so placement never reaches into a chunk
 * that is not generated yet. A wall plant's search also reads the blocks beside its column, one
 * or two blocks further out, which is still inside the area the game has generated by then.
 */
public final class PlantWorldGenerator implements IWorldGenerator {

    /** Candidate columns tried per successful roll. The performance bound in the requirements. */
    static final int CANDIDATES = 16;

    private final PlantRegistry registry;
    private final PlacementCheck check;

    public PlantWorldGenerator(PlantRegistry registry, PlacementCheck check) {
        this.registry = registry;
        this.check = check;
    }

    @Override
    public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator chunkGenerator,
                         IChunkProvider chunkProvider) {
        boolean debug = registry.debugLog();
        for (PlantDefinition plant : registry.plants()) {
            BlockPlantBase block = registry.blockOf(plant);
            // The two cheapest rules are asked up front so a disabled or out-of-dimension plant
            // costs no candidate positions at all; the check below asks them again as the one
            // owner of the answer, at no meaningful cost.
            PlantSettings settings = registry.settings(plant);
            if (!settings.enabled() || !PlacementCheck.dimensionMatches(world, plant.dimension())) {
                continue;
            }
            if (random.nextInt(100) >= settings.chunkChancePercent()) {
                continue;
            }
            for (int attempt = 0; attempt < CANDIDATES; attempt++) {
                int x = chunkX * 16 + 8 + random.nextInt(16);
                int z = chunkZ * 16 + 8 + random.nextInt(16);
                // The biome is a property of the column, so it is asked before the costlier search.
                if (!check.biomeAllows(world, new BlockPos(x, 0, z), plant)) {
                    continue;
                }
                BlockPos pos = CandidateFinder.find(world, plant, x, z, random);
                if (pos == null) {
                    continue;
                }
                if (check.check(world, pos, plant, false) != null) {
                    continue;
                }
                PlantStage stage = block.lifecycle().initialStage(world, pos);
                IBlockState state = block.placedState(world, pos, stage);
                world.setBlockState(pos, state, 2);
                if (debug) {
                    // The whole state, so the log shows the stage and, for a wall plant, its facing.
                    ElusiveFloraLog.LOGGER.info("Placed {} at {} {} {}", state,
                            pos.getX(), pos.getY(), pos.getZ());
                }
                break;
            }
        }
    }
}
